### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by izaa** [voximplant/react-native-demo#17]
Hi,

I was able to login using previous version of the code but this version gives me:

"Login failed: error code: 500" it 

How could I debug this info?  It seems that no matter what password I use, the same error remains.

Thank you for the great API and demo!

**Comment by YuliaGrigorieva** [comment]
Hello!

Please check Xcode or logcat output and find the logs from Voximplant SDK (tagged with VOXSDK on android or VI on iOS) related to login operation. It should contain more information about the root cause of the issue.

If the logs do not help you with the issue, please send them to support@voximplant.com and we will investigate them.

Best regards,
Yulia Grigorieva

**Comment by izaa** [comment]
Wasn't connected correctly. If I log in from onConnected-hook then works nice. Can be closed thanks :)
