### ISSUE TITLE
cannot understand remoteData.voximplant = notif.voximplant 

### ISSUE THREAD

**Issue by izaa** [voximplant/react-native-demo#19]
Hi,

i cannot understand this part of the code

`remoteData.voximplant = notif.voximplant;`

since it seems that notif does not have voximplant property. Can you explain a bit more? Thank you!

```
FCM.on(FCMEvent.Notification, async (notif) => {
    var remoteData = {};
    remoteData.voximplant = notif.voximplant;
    pushManager.pushNotificationReceived(remoteData);
});
```

**Comment by YuliaGrigorieva** [comment]
Hello!

Firebase remote message that should be provided to Voximplant sdk is of type Map<String, String> and it has "voximplant" key (as you see we use notif.voximplant).

However react-native-fcm module that is used in this demo provides notification with extra data and it throws exception "ReadableNativeMap cannot be casted to java.lang.String" caused by notif.fcm property.

To avoid this, we get required data from **notif** object and process only that data in the demo application.

You can put a breakpoint to see the content of the **notif** object and  also try passing the **notif** object as is to the "pushManager.pushNotificationReceived" method in order to see the exception.

Best  regards,
Yulia Grigorieva
